seed: 42
dt: 0.01
t_horizon: 5.0
window: 30
ema_alpha: 0.1
shrinkage: 0.05
jitter: 1e-6
det_clamp: 1e-12
gamma: 0.5
alpha: 0.6
beta: 0.02
kappa: 0.12
use_adaptive_gain: true
grid:
  eta: [0.5, 1.0, 1.5, 2.0, 2.5, 3.0]
  lambda: [0.5, 1.0, 1.5, 2.0, 2.5]
