seed: 42
dt: 0.01
t_horizon: 5.0
window: 30
ema_I: 0.1
shrinkage: 0.05
jitter: 1e-6
det_clamp: 1e-12
noise_std: 0.005

# System parameters
eta: 1.0
lambda: 1.2
gamma: 0.5
alpha_sat: 0.6
beta_sat: 0.02
kappa_couple: 0.12

# Adaptive eta (whitening gain)
adaptive_eta:
  enabled: true
  epsilon: 1e-12
  cap: 15.0
  d_scale: 6  # dimensionality override for gain normalization
  ema_alpha: 0.1

# Grid for sweeps
grid:
  eta: [0.5, 1.0, 1.5, 2.0, 2.5, 3.0]
  lambda: [0.5, 1.0, 1.5, 2.0, 2.5]
