concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: gp-demo

on:
  push:
  pull_request:

jobs:
  demo:
    runs-on: ubuntu-latest
    env:
      RG_CI: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Run GP ringing demo (light mode)
        run: |
          python experiments/gp_ringing_demo.py \
            --steps 180 --runs 200 --seeds 1 \
            --beta 0.9 --alpha 0.08 --tau 40.0 \
            --out results/gp_demo
          cat results/gp_demo/ringing_demo_summary.json
      - name: Upload GP demo summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gp-demo-summary
          path: results/gp_demo/ringing_demo_summary.json
