# Equilibrium Sweep Configuration
# Parameters for Jacobian eigenvalue analysis
# Used by scripts/equilibrium_analysis.py

seed: 42

alpha:
  start: 0.10
  stop: 1.00
  step: 0.01

model:
  K0: 1.2           # drive amplitude
  gamma: 0.08       # damping coefficient
  omega0_sq: 1.0    # natural frequency squared

solver:
  tol: 1e-10        # equilibrium solver tolerance
  max_iter: 10000   # maximum solver iterations

jacobian:
  mode: "analytic"  # options: "analytic" or "finite_diff"
