#!/bin/bash
# CODEX workflow: Run experiments and publish to Pages

set -e  # Exit on error

echo "🌊 CODEX Automated Experiment Runner"
echo "===================================="

# Parse arguments
EXPERIMENT=${1:-poison}  # Default to poison detection
DRY_RUN=${2:-false}

echo "Experiment: $EXPERIMENT"
echo "Dry run: $DRY_RUN"
echo ""

# Navigate to repo root
cd "$(git rev-parse --show-toplevel)"

# 1. RUN EXPERIMENT
echo "📊 Step 1: Running experiment..."

case $EXPERIMENT in
  poison)
    echo "Running poison detection demo..."
    cd experiments/poison_detection
    pip install -q -r requirements.txt
    python demo_poison_detection.py
    cd ../..
    ;;

  gp)
    echo "Running GP ringing demo..."
    python experiments/gp_ringing_demo.py --steps 500 --runs 2000 --seeds 2
    ;;

  *)
    echo "Unknown experiment: $EXPERIMENT"
    exit 1
    ;;
esac

echo "✓ Experiment completed"
echo ""

# 2. PUBLISH RESULTS
echo "📤 Step 2: Publishing results to Pages..."

python scripts/publish_results.py $EXPERIMENT

echo "✓ Results published"
echo ""

# 3. COMMIT AND PUSH
if [ "$DRY_RUN" = "false" ]; then
    echo "📝 Step 3: Committing results..."

    git add docs/data/

    TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M UTC")
    git commit -m "Results: $EXPERIMENT experiment results - $TIMESTAMP

Auto-generated by CODEX workflow
- Ran $EXPERIMENT experiment
- Published results to docs/data/
- Updated Pages content"

    echo "✓ Committed"
    echo ""

    echo "⬆️ Step 4: Pushing to GitHub..."
    git push

    echo "✓ Pushed"
    echo ""

    echo "🚀 Results will be live at:"
    echo "   https://justindbilyeu.github.io/Resonance_Geometry/$EXPERIMENT/"
    echo ""
    echo "Pages deployment typically takes 1-2 minutes."
else
    echo "🔍 DRY RUN: Skipping commit and push"
    echo ""
    echo "Files ready to commit:"
    git status --short docs/data/
fi


echo ""
echo "✅ Workflow complete!"
