name: Build Papers (PDF + ZIP)

on:
  push:
    paths:
      - 'docs/papers/**'
      - '.github/workflows/build-papers.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-latex-extra texlive-fonts-recommended lmodern

      - name: Build NeurIPS paper PDF
        run: |
          set -e
          mkdir -p build/papers
          P=docs/papers/neurips/A_Geometric_Theory_of_AI_Hallucination.md
          if [ ! -f "$P" ]; then
            echo "Paper not found: $P"
            exit 1
          fi
          - name: Install TeX Live (xelatex)
  run: |
    sudo apt-get update
    sudo apt-get install -y \
      texlive-xetex \
      texlive-latex-recommended \
      texlive-fonts-recommended \
      texlive-lang-other
          pandoc "$P" \
            --from markdown+tex_math_dollars \
            --pdf-engine=xelatex \
            -V geometry:margin=1in \
            -o build/papers/Geometric_Hallucination.pdf

      - name: Collect figures and CSVs
        run: |
          mkdir -p build/papers/figures build/papers/results
          cp -n papers/neurips/figures/*.png build/papers/figures/ 2>/dev/null || true
          cp -n papers/neurips/results/*.csv build/papers/results/ 2>/dev/null || true

      - name: Make ZIP bundle
        run: |
          cd build
          zip -r Geometric_Hallucination_bundle.zip papers

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: geometric-hallucination-pdf-and-zip
          path: |
            build/papers/Geometric_Hallucination.pdf
            build/Geometric_Hallucination_bundle.zip
