name: build-papers

on:
  push:
    paths:
      - 'docs/papers/neurips/**'
      - '.github/workflows/build-papers.yml'
  pull_request:

jobs:
  build-neurips-paper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Pandoc + TeX Live (xelatex)
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Build PDF (NeurIPS)
        run: |
          set -e
          test -f docs/papers/neurips/manuscript.md
          mkdir -p docs/papers/neurips/pdfs
          pandoc docs/papers/neurips/manuscript.md \
            --from gfm \
            --pdf-engine=xelatex \
            --resource-path=docs/papers/neurips:docs/papers/neurips/figures \
            -o docs/papers/neurips/pdfs/A_Geometric_Theory_of_AI_Hallucination.pdf

      - name: Upload PDF artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: neurips-paper-pdf
          path: docs/papers/neurips/pdfs/*.pdf
