name: Build Papers (disabled; superseded by dissertation-build)

on:
  workflow_call: {}   # keep file in repo but disable automatic triggers

jobs:
  build:
    if: ${{ false }}  # hard-disable this job until re-enabled
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: No-op
        run: echo "Legacy paper build disabled. Use dissertation-build.yml for all Pandoc/TeX builds."
