name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up git safe directory (CI containers)
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Run pre-commit lint
        run: pre-commit run -a

      # --- Unit tests ---
      - name: Run tests
        run: pytest -q --disable-warnings

      # --- Ringing sweep (fast, deterministic) ---
      - name: Run ringing sweep
        run: |
          make ring-sweep || echo "Ringing sweep skipped"

      - name: Update theory status
        run: |
          make theory-status || true

      - name: Upload ringing artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ringing-sweep
          path: |
            results/ringing_sweep/*.json*
            docs/reports/ringing_boundary.md
          if-no-files-found: ignore

      # --- OPTIONAL: Fluency sweep (might not exist yet) ---
      - name: Run fluency sweep (optional)
        run: |
          if [ -f scripts/run_fluency_probe.py ]; then
            python scripts/run_fluency_probe.py || echo "Fluency sweep failed/absent; continuing"
          else
            echo "scripts/run_fluency_probe.py not found; skipping fluency sweep"
          fi
        continue-on-error: true

      - name: Upload fluency artifacts (optional)
        if: ${{ hashFiles('results/fluency_sweep/*.json*','docs/reports/fluency_velocity.md','docs/assets/figures/fluency_map.png') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: fluency-results
          path: |
            results/fluency_sweep/*.json*
            docs/reports/fluency_velocity.md
            docs/assets/figures/fluency_map.png
          if-no-files-found: warn
