name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Run pre-commit lint
        run: pre-commit run -a

      - name: Run tests
        run: pytest -q --disable-warnings

      - name: Phase 3 — Fluency Sweep
        run: |
          make fluency-sweep
          make fluency-status

      - name: Upload Fluency Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fluency-sweep
          path: |
            results/fluency_sweep/*.json*
            docs/reports/fluency_velocity.md
            docs/assets/figures/fluency_map.png

      - name: Ringing sweep (with Jacobian)
        run: make jacobian-sweep

      - name: Fluency probe
        run: make fluency-probe

      - name: Update dashboard status
        run: make theory-status

      - name: Upload diagnostics artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: phase2-3-artifacts
          path: |
            results/ringing_sweep/*.json*
            results/fluency_probe/summary.json
            docs/data/status/summary.json
