name: gp-demo

on:
  pull_request:
    paths:
      - 'gp-demo/**'
      - 'rg/**'
      - '.github/workflows/gp-demo.yml'
  push:
    branches: [ main ]
    paths:
      - 'gp-demo/**'
      - 'rg/**'
      - '.github/workflows/gp-demo.yml'
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  demo:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements*.txt
            pyproject.toml
            setup.cfg
            setup.py

      - name: Install project (editable) + tests
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -U pytest numpy matplotlib

      - name: Ensure figures dir exists
        run: mkdir -p figures

      - name: Run GP ringing demo (smoke)
        env:
          RG_CI: "1"
          MPLBACKEND: Agg
        run: |
          python experiments/gp_ringing_demo.py --smoke --out figures/gp_ringing_smoke.png

      - name: Upload figures (artifacts)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gp-demo-figures
          path: figures/
          if-no-files-found: warn
          retention-days: 14
