name: gp-demo

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '.github/**'
  pull_request:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install project (editable) + tests
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest

      - name: Run tests
        run: pytest -q

      - name: Run GP ringing demo (smoke mode)
        env:
          RG_CI: '1'
        run: |
          mkdir -p figures
          python experiments/gp_ringing_demo.py --smoke --out figures/gp_ringing_smoke.png || true

      - name: Upload figures (artifacts)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gp-demo-figures
          path: figures/
