name: gp demos smoke

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install project (editable)
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -q

      - name: Run GP ringing demo
        env:
          MPLBACKEND: Agg
          RG_CI: "1"
        run: python experiments/gp_ringing_demo.py

      - name: Run optimized spin-foam smoke
        env:
          MPLBACKEND: Agg
          RG_CI: "1"
        run: |
          python experiments/spin_foam_smoke.py --steps 5000 --size 16 --runs 4 --seed 7

      - name: Upload figures (artifacts)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gp-demo-figures
          path: figures/
          if-no-files-found: ignore
