name: Deploy GitHub Pages
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate docs build
        run: |
          test -d docs || mkdir docs
          echo "Docs directory present."
      - name: Copy figures & results (best-effort)
        run: |
          mkdir -p docs/results docs/figures
          # Mirror common outputs if present; ignore errors
          rsync -a --ignore-missing-args results/ docs/results/ || true
          rsync -a --ignore-missing-args figures/ docs/figures/ || true
      - name: Build unified dashboard
        run: |
          python scripts/update_theory_status.py
          python scripts/build_dashboard.py
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
