name: Build Whitepaper (Pandoc → HTML+PDF)

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/whitepaper'
      - '.github/workflows/pandoc-build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pandoc & TeX (full enough for xelatex)
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          sudo apt-get install -y \
            texlive-xetex \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            lmodern

      - name: Ensure Pages folder and nojekyll
        run: |
          mkdir -p docs
          touch docs/.nojekyll

      - name: Build HTML with MathJax
        run: |
          pandoc docs/whitepaper \
            --from=latex --to=html5 \
            --mathjax \
            --metadata title="Resonance Geometry v1.0" \
            -s -o docs/index.html

      - name: Build PDF (XƎLaTeX with fallback)
        run: |
          pandoc docs/whitepaper -o docs/whitepaper.pdf --pdf-engine=xelatex || \
          pandoc docs/whitepaper -o docs/whitepaper.pdf --pdf-engine=pdflatex

      - name: Commit build artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/index.html docs/whitepaper.pdf docs/.nojekyll || true
          if ! git diff --cached --quiet; then
            git commit -m "Build Pages: HTML+PDF from LaTeX"
            git push
          fi
