# DISABLED — superseded by build-papers.yml
name: Build Whitepaper (Pandoc → HTML+PDF)

on:
  pull_request:
    paths: [ '__disabled__/**' ]
  push:
    paths: [ '__disabled__/**' ]
  workflow_dispatch: {}

jobs:
  build:
    if: false  # DISABLED — superseded by build-papers.yml
    runs-on: ubuntu-latest
    steps:
      - run: echo "disabled"
