name: Build paper figures

on:
  pull_request:
    paths:
      - 'Makefile'
      - 'scripts/equilibrium_analysis.py'
      - 'results/phase/traces/**'
      - 'docs/analysis/**'
      - 'figures/**'
      - '.github/workflows/paper-figs.yml'
  push:
    branches:
      - main
      - 'paper/**'
    paths:
      - 'Makefile'
      - 'scripts/equilibrium_analysis.py'
      - 'results/phase/traces/**'
      - 'docs/analysis/**'
      - 'figures/**'
      - '.github/workflows/paper-figs.yml'
  workflow_dispatch:

jobs:
  build-paper-figures:
    name: Build paper figures
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          fi
          python -m pip install numpy scipy matplotlib pandas

      - name: Build artifacts
        run: make paper-figs

      - name: Install LaTeX dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-extra texlive-fonts-recommended inkscape

      - name: Compile non-Hopf paper PDF
        working-directory: docs/papers/non_hopf
        run: |
          pdflatex -interaction=nonstopmode non_hopf_paper_draft_v1.tex || true
          bibtex non_hopf_paper_draft_v1 || true
          pdflatex -interaction=nonstopmode non_hopf_paper_draft_v1.tex || true
          pdflatex -interaction=nonstopmode non_hopf_paper_draft_v1.tex || true

      - name: Upload figure artifacts
        uses: actions/upload-artifact@v4
        with:
          name: paper-figs-artifacts
          path: |
            figures/eigenvalue_real_vs_alpha.png
            docs/analysis/eigs_scan_alpha.csv
            docs/analysis/eigs_scan_summary.json
            results/phase/traces/*.json
          if-no-files-found: error

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: non_hopf_paper_v1
          path: docs/papers/non_hopf/non_hopf_paper_draft_v1.pdf
          if-no-files-found: warn
