name: Poison Detection Smoke Test

on:
  push:
    paths:
      - 'experiments/poison_detection/**'
      - 'docs/poison_detection/**'
      - '.github/workflows/poison-detection-test.yml'
  pull_request:
    paths:
      - 'experiments/poison_detection/**'
      - 'docs/poison_detection/**'
      - '.github/workflows/poison-detection-test.yml'
  workflow_dispatch:

jobs:
  smoke-test:
    if: vars.ENABLE_POISON_DETECTION_TESTS == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r experiments/poison_detection/requirements.txt

      - name: Run smoke test
        working-directory: experiments/poison_detection
        run: |
          python -c "from rg_detector import RGPoisonDetector; print('✓ RGPoisonDetector import OK')"
