# .github/workflows/rwp-ci.yml
name: rwp-core CI
on:
  push:
    paths:
      - 'src/**'
      - 'rwp/**'
      - 'scripts/**'
      - 'pyproject.toml'
      - 'requirements*.txt'
      - '.github/workflows/rwp-ci.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'rwp/**'
      - 'scripts/**'
      - 'pyproject.toml'
      - 'requirements*.txt'
      - '.github/workflows/rwp-ci.yml'
jobs:
  test-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt || true
          pip install -e . || true
          pip install numpy scipy matplotlib pytest
      - name: Unit tests
        run: |
          set -e
          pytest -q || code=$?
          # pytest exit code 5 == "no tests collected"
          if [ "${code:-0}" = "5" ]; then
            echo "No tests collected; treating as pass for this workflow."
            exit 0
          elif [ -n "${code:-}" ] && [ "$code" != "0" ]; then
            exit "$code"
          fi
      - name: Smoke experiment (ringing tiny)
        run: |
          python - <<'PY'
          import os, numpy as np
          from pathlib import Path
          # replace with your callable once rwp.experiments.ringing exists
          Path("results/ci/").mkdir(parents=True, exist_ok=True)
          import json
          json.dump({"ok": True, "note": "placeholder until experiments wired"}, open("results/ci/smoke.json","w"))
          print("Wrote results/ci/smoke.json")
          PY
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rwp-results
          path: results/**
