name: Simulations

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  simulate:
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' &&
       contains(join(github.event.pull_request.labels.*.name, ','), 'run-heavy'))
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-sims-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-sims-

      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Run smoke simulations
        run: |
          if [ -d simulations ]; then
            echo "Running lightweight simulations under ./simulations"
            pytest -q simulations --maxfail=1 || echo "No simulation tests found"
          else
            echo "No ./simulations directory found; skipping."
          fi
        continue-on-error: ${{ github.event_name == 'pull_request' }}

      - name: Document deferred heavy simulations
        run: echo "Heavy simulations deferred. Run locally if needed."
